package com.lkz.cardholder.dao;

import com.lkz.cardholder.Domain.Mycard;
import com.lkz.cardholder.Domain.MycardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MycardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    long countByExample(MycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    int deleteByExample(MycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    int insert(Mycard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    int insertSelective(Mycard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Mycard selectOneByExample(MycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Mycard selectOneByExampleSelective(@Param("example") MycardExample example, @Param("selective") Mycard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Mycard> selectByExampleSelective(@Param("example") MycardExample example, @Param("selective") Mycard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    List<Mycard> selectByExample(MycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Mycard selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Mycard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    Mycard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Mycard selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Mycard record, @Param("example") MycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Mycard record, @Param("example") MycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Mycard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Mycard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MycardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mycard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}